name: Send Daily Quiz

on:
  schedule:
    # Время в UTC (Алматы -5 часов)
    # 11:13 по Алматы (06:13 UTC)
    - cron: '13 6 * * *'  
    # 14:27 по Алматы (09:27 UTC)
    - cron: '27 9 * * *'  
    # 17:42 по Алматы (12:42 UTC)
    - cron: '42 12 * * *' 
  workflow_dispatch: # Кнопка для ручного запуска

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install aiogram

      - name: Run bot
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        run: |
          # Получаем текущий час в UTC
          H=$(date -u +%H)
          echo "Current UTC hour: $H"

          # Логика выбора тега по интервалам (UTC):
          # Если запуск в промежутке 05:00 - 08:59 UTC -> Swift
          if [ "$H" -ge 5 ] && [ "$H" -lt 9 ]; then
            TAG="Swift"
          
          # Если запуск в промежутке 09:00 - 11:59 UTC -> Kotlin
          elif [ "$H" -ge 9 ] && [ "$H" -lt 12 ]; then
            TAG="Kotlin"
          
          # Если запуск в промежутке 12:00 - 15:59 UTC -> Flutter
          elif [ "$H" -ge 12 ] && [ "$H" -lt 16 ]; then
            TAG="Flutter"
          
          # Запасной вариант на случай ночного запуска
          else
            TAG="Flutter"
          fi

          echo "Selected TAG based on interval: $TAG"
          python bot.py $TAG